#######################################################################################
# Book settings
title : Data Engineering for Everybody
author: PseudoLab
logo: 'PseudoLab_logo.png'

# Short description about the book
description: >-
  Data Engineering Book about Data, by Data, for Data!

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : off

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/pseudo-lab/data-engineering-for-everybody
  path_to_book                : "book"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
    
html:
  favicon: 'PseudoLab_logo.png'
  use_issues_button: true
  use_repository_button: true
  
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

parse:
  myst_enable_extensions:
    - html_image
